// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2ZweqLd2p_RhpLJfIQ9N7cUkWMmCR3o',
    appId: '1:201310730278:android:76f6c6ff26d7e99ca54ee7',
    messagingSenderId: '201310730278',
    projectId: 'login-86404',
    storageBucket: 'login-86404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5lG_JWQeoJiJP5fwwbW9V0iZWmNC-s4',
    appId: '1:201310730278:ios:bc4c672da56955c8a54ee7',
    messagingSenderId: '201310730278',
    projectId: 'login-86404',
    storageBucket: 'login-86404.appspot.com',
    androidClientId: '201310730278-2i8p0fl91alb0jjj9oc981ddvd1aev5q.apps.googleusercontent.com',
    iosClientId: '201310730278-pbu97a7sli6uo0va2b51rbofost7ll7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLoginsFlutter',
  );
}
